name: dartnet
version: 0.1.2
description: Configurable http server in dart.
author: Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/lejard-h/dartnet

executables:
  dartnet:

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  jaguar: '>=0.4.0 <0.5.0'
  jaguar_mustache: '>=0.4.0 <0.5.0'
  ansicolor: ">=0.0.9 <0.1.0"
  resource: '>=2.0.0 <3.0.0'
  yamlicious: ">=0.0.5 <0.1.0"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
