name: dartnet
version: 0.3.0
description: Configurable http server in dart.
author: Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/lejard-h/dartnet

executables:
  dartnet:

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  jaguar: ^2.4.0
  ansicolor: ^1.0.2
  yaml: ^2.1.15
  resource: ^2.1.5
  mustache: ^1.0.2
  logging: ^0.11.3+2
  path: ^1.6.2
  args: ^1.5.1

dev_dependencies:
  test: ^1.3.0
