name: dartnet
version: 0.2.0
description: Configurable http server in dart.
author: Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/lejard-h/dartnet

executables:
  dartnet:

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  jaguar: ^2.4.0
  ansicolor:
  yaml:
  resource:
  mustache:

dev_dependencies:
  test: ^1.3.0
